SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `AUTH_GROUP` (
  `AUTH_GROUP_NAME` VARCHAR(35)  NOT NULL,
  `DESCRIPTION`     VARCHAR(355) NOT NULL,
  `CREATED_AT`      BIGINT(20)   NOT NULL,
  `UPDATED_AT`      BIGINT(20)   NOT NULL,
  PRIMARY KEY (`AUTH_GROUP_NAME`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `AUTH_GROUP_ROLE` (
  `AUTH_GROUP_ROLE_ID` INT(11)     NOT NULL AUTO_INCREMENT,
  `AUTH_ROLE_NAME`     VARCHAR(25) NOT NULL,
  `AUTH_GROUP_NAME`    VARCHAR(35) NOT NULL,
  `CREATED_AT`         BIGINT(20)  NOT NULL,
  `UPDATED_AT`         BIGINT(20)  NOT NULL,
  PRIMARY KEY (`AUTH_GROUP_ROLE_ID`),
  KEY `group_group_role_fk` (`AUTH_GROUP_NAME`),
  KEY `role_group_role_fk` (`AUTH_ROLE_NAME`),
  CONSTRAINT `group_group_role_fk` FOREIGN KEY (`AUTH_GROUP_NAME`) REFERENCES `AUTH_GROUP` (`AUTH_GROUP_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_group_role_fk` FOREIGN KEY (`AUTH_ROLE_NAME`) REFERENCES `AUTH_ROLE` (`AUTH_ROLE_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE =InnoDB
  AUTO_INCREMENT =34
  DEFAULT CHARSET =utf8;

CREATE TABLE `AUTH_ROLE` (
  `AUTH_ROLE_NAME` VARCHAR(25)  NOT NULL,
  `DESCRIPTION`    VARCHAR(355) NOT NULL,
  `CREATED_AT`     BIGINT(20)   NOT NULL,
  `UPDATED_AT`     BIGINT(20)   NOT NULL,
  PRIMARY KEY (`AUTH_ROLE_NAME`),
  KEY `DESCRIPTION_IDX` (`DESCRIPTION`(255))
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

CREATE TABLE `PROPERTY` (
  `PROPERTY_KEY` VARCHAR(255)  NOT NULL,
  `VALUE`        VARCHAR(1255) NOT NULL,
  PRIMARY KEY (`PROPERTY_KEY`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

SET FOREIGN_KEY_CHECKS = 1;
